# Generated by Django 5.1.1 on 2024-09-29 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название языка')),
            ],
        ),
        migrations.CreateModel(
            name='LessonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название темы')),
                ('description', models.TextField(verbose_name='Теория')),
                ('programing_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studyProgram.programinglanguage')),
            ],
        ),
    ]
