# Generated by Django 5.1 on 2024-10-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyProgram', '0004_student_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='programing_language',
        ),
    ]
