# Generated by Django 5.1 on 2024-11-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyProgram', '0005_remove_problem_programing_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonname',
            options={'verbose_name': 'Название урока', 'verbose_name_plural': 'Названия уроков'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='programinglanguage',
            options={'verbose_name': 'Язык программирования', 'verbose_name_plural': 'Языки программирования'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'Попытка', 'verbose_name_plural': 'Попытки'},
        ),
        migrations.AddField(
            model_name='lessonname',
            name='picture',
            field=models.ImageField(null=True, upload_to='students', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('2', 'WAIT'), ('1', 'OK'), ('0', 'FAIL')], default='2', max_length=1, verbose_name='Статус'),
        ),
    ]
